name: Build and List Demo Docker Images

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-list:
    name: 'Build and List Demo Docker Images'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Images
      - name: Build and push demo images
        run: |
          # Clean previous URL list
          # rm -f image_urls.txt

          # Loop through demo Dockerfiles
          for file in demo_examples/Dockerfile_*; do
            # Extract the base name of the Dockerfile (e.g., vuln1, fixed1)
            IMAGE_TYPE=$(basename $file | sed 's/Dockerfile_//')
            # IMAGE_NAME="$DOCKER_USERNAME/cve:${IMAGE_TYPE}"
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/cve:${IMAGE_TYPE}"
            # Build and push the Docker image
            docker build -t $IMAGE_NAME -f $file .
            docker push $IMAGE_NAME

            # Append the public URL to image_urls.txt
            echo "docker.io/${IMAGE_NAME}" >> image_urls.txt
          done

          # Debug: Output the contents of image_urls.txt
          cat image_urls.txt


      # Step 4: Upload image_urls.txt
      - name: Upload image URL list
        uses: actions/upload-artifact@v4
        with:
          name: image-urls
          path: image_urls.txt
